############################################################
# Dockerfile to build nginx container image
# Based on nginx
############################################################

FROM nginx
MAINTAINER Alzamly Hossam
COPY nginx.conf /etc/nginx/nginx.conf
# COPY htmlphp /usr/share/nginx/html

# CMD systemctl restart nginx

